apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: project  
spec:
  selector:
    matchLabels:
      app: mysql
      project: project
      tier: db      
  serviceName: "mysql" # This should reference the headless service
  replicas: {{ .Values.statefulset.replicas }} # Number of MySQL replicas
  minReadySeconds: 10 # Time to wait before considering the pod ready
  template:
    metadata:
      labels:
        app: mysql # Must match .spec.selector.matchLabels
        project: project
        tier: db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: {{ .Values.statefulset.image }}
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql
      namespace: project
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc" # Ensure this StorageClass exists in your cluster
      resources:
        requests:
          storage: {{ .Values.statefulset.storage }}
