# Headless Service for StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: project
  labels:
    app: mysql
    project: project
    tier: db
spec:
  clusterIP: None  # Important for headless service, no IP will be assigned to the service
  selector:
    app: mysql
    project: project
    tier: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
# Normal Service
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: project
  labels:
    app: mysql
    project: project
    tier: db
spec:
  selector: # labels will be used here for selecting the pod
    app: mysql
    project: project
    tier: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306